version: '3'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    #mem_limit: 20m
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 20M
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      - DEFAULT_HOST=bobkubista.com

  web:
    build: ./static_http
    #mem_limit: 10m
    deploy:
      #replicas: 2
      resources:
        limits:
          cpus: '0.10'
          memory: 10M
    restart: always
    environment:
      - VIRTUAL_HOST=bobkubista.com
