version: '2'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    mem_limit: 20m
    restart: always
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      - DEFAULT_HOST=bobkubista.com

  web:
    build: ./static_http
    mem_limit: 10m
    restart: always
    environment:
      - VIRTUAL_HOST=bobkubista.com
