
nexus:
  build: ./nexus
  ports:
    - "8081:8081"

jenkins:
  build: ./jenkins
  
  ports:
    - "50000:50000"
    - "8080:8080"
    
  volumes:
    - /opt/jenkins_home:/var/jenkins_home

  depens_on:
    - nexus
    - sonar
  
  environment:
    - NEXUS_PORT=8081
    - SONAR_PORT=9000
    - SONAR_DB_PORT=5432

sonar:
  build: ./sonar
  ports:
    - "9000:9000"
    - "5432:5432"
  environment:
    - SONARQUBE_JDBC_URL=jdbc:postgresql://192.168.1.107:5432/sonar
    - SONARQUBE_JDBC_USERNAME=sonar
    - SONARQUBE_JDBC_PASSWORD=sonar


  #TODO setup plugins
  #TODO ...