apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 2
  template:
    spec:
      containers:
      - env:
        image: web:latest
        imagePullPolicy: Always
        name: web
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 100m
            memory: "10485760"
      restartPolicy: Always